version: '3.8'

services:
  postgres:
    build: ./services/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dashboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dashboard:
    build: ./services/dashboard
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dashboard_db
    ports:
      - "6061:6061"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        sleep 5 &&
        python seed_data.py &&
        uvicorn main:app --host 0.0.0.0 --port 6061 --reload
      "

volumes:
  postgres_data:
